"""
Similarity Search Results Visualization
Analyzes patent flag results from similarity searches
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from pathlib import Path
import argparse

def analyze_csv_file(file_path):
    """Analyze a CSV file and return patent counts"""
    if not Path(file_path).exists():
        return None, None, None
    
    try:
        df = pd.read_csv(file_path)
        total = len(df)
        patented = (df['is_patented'] == True).sum()
        non_patented = (df['is_patented'] == False).sum()
        return patented, non_patented, total
    except:
        return None, None, None

def main():
    parser = argparse.ArgumentParser(
        description='Visualize similarity search results from patent flagging',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python similarity_comparison.py
  python similarity_comparison.py --similarity similarity --output results.png
  python similarity_comparison.py -s ./similarity -o output/comparison.png
        """
    )
    
    parser.add_argument(
        '-s', '--similarity',
        type=str,
        default='similarity',
        help='Path to similarity results directory (default: similarity)'
    )
    parser.add_argument(
        '-o', '--output',
        type=str,
        default='visualizations/similarity_comparison.png',
        help='Output path for visualization (default: visualizations/similarity_comparison.png)'
    )
    
    args = parser.parse_args()
    
    similarity_dir = Path(args.similarity)
    output_file = args.output
    
    # File pairs to compare (exact vs scaffold)
    files_info = {
        'generated_set': [
            ('tanimoto_ro5_compliant_molecules', 'tanimoto_ro5_compliant_molecules'),
            ('all_generated_mol', 'all_generated_mol'),
            ('top_10_molecules', 'top10_molecules'),
        ],
        'training_dataset': [
            ('training_dataset', 'training_dataset'),
        ]
    }
    
    results = []
    
    print("\nAnalyzing Similarity Search Results")
    print("="*80)
    print("\nDATASET LEGEND:")
    print("-"*80)
    print("All Generated Mol      → All molecules generated by the model")
    print("Tanimoto Ro5           → Molecules from generated molecules that passed")
    print("                         the computational screening (Tanimoto Similarity Scoring (<= 0.7) and Lipinski Rule of 5)")
    print("Top 10 Molecules       → Top 10 molecules from the DTI (DeepPurpose)")
    print("Training Dataset       → Original training dataset")
    print("="*80)
    
    for category, file_pairs in files_info.items():
        print(f"\n{category.upper()}")
        print("-"*80)
        
        for data_name, scaffold_name in file_pairs:
            full_file = similarity_dir / category / f"{data_name}_exact_flag.csv"
            scaffold_file = similarity_dir / category / f"{scaffold_name}_scaffold_flag.csv"
            
            full_pat, full_non, full_total = analyze_csv_file(full_file)
            scaffold_pat, scaffold_non, scaffold_total = analyze_csv_file(scaffold_file)
            
            if full_total:
                full_rate = (full_pat / full_total * 100) if full_total > 0 else 0
                results.append({
                    'File': data_name.replace('_', ' ').title(),
                    'Category': category,
                    'Type': 'Full',
                    'Patented': full_pat,
                    'Not Patented': full_non,
                    'Total': full_total,
                    'Patented %': full_rate
                })
                print(f"{data_name:40} | FULL     | Total: {full_total:4d} | Patented: {full_pat:4d} ({full_rate:5.1f}%) | Not: {full_non:4d}")
            
            if scaffold_total:
                scaffold_rate = (scaffold_pat / scaffold_total * 100) if scaffold_total > 0 else 0
                results.append({
                    'File': data_name.replace('_', ' ').title(),
                    'Category': category,
                    'Type': 'Scaffold',
                    'Patented': scaffold_pat,
                    'Not Patented': scaffold_non,
                    'Total': scaffold_total,
                    'Patented %': scaffold_rate
                })
                print(f"{data_name:40} | SCAFFOLD | Total: {scaffold_total:4d} | Patented: {scaffold_pat:4d} ({scaffold_rate:5.1f}%) | Not: {scaffold_non:4d}")
    
    df = pd.DataFrame(results)
    
    # Create visualization
    fig, ax2 = plt.subplots(figsize=(14, 6))
    
    exact_df = df[df['Type'] == 'Full'].copy()
    scaffold_df = df[df['Type'] == 'Scaffold'].copy()
    
    # Get all files, including those with only one version
    all_files = sorted(set(exact_df['File'].tolist() + scaffold_df['File'].tolist()))
    
    # Create position-based plotting
    x_pos = []
    full_rates = []
    scaffold_rates = []
    x_labels = []
    
    for file_name in all_files:
        full_data = exact_df[exact_df['File'] == file_name]
        scaffold_data = scaffold_df[scaffold_df['File'] == file_name]
        
        if len(full_data) > 0:
            full_rates.append(full_data['Patented %'].values[0])
        else:
            full_rates.append(0)
            
        if len(scaffold_data) > 0:
            scaffold_rates.append(scaffold_data['Patented %'].values[0])
        else:
            scaffold_rates.append(0)
        
        x_pos.append(len(x_pos))
        x_labels.append(file_name)
    
    width = 0.35
    
    ax2.bar([i - width/2 for i in x_pos], full_rates, width, 
            label='Full', color='steelblue', alpha=0.8)
    ax2.bar([i + width/2 for i in x_pos], scaffold_rates, width, 
            label='Scaffold', color='coral', alpha=0.8)
    
    ax2.set_ylabel('Patented Percentage (%)', fontsize=11, fontweight='bold')
    ax2.set_title('Patent Hit Rate: Full vs Scaffold', fontsize=12, fontweight='bold')
    ax2.set_xticks(x_pos)
    ax2.set_xticklabels(x_labels, rotation=45, ha='right', fontsize=9)
    ax2.set_ylim(0, 100)
    ax2.legend()
    ax2.grid(axis='y', alpha=0.3)
    
    fig.suptitle('Similarity Checking Tanimoto Threshold: 95%', fontsize=14, fontweight='bold', y=0.98)
    
    plt.tight_layout()
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n✓ Visualization saved as '{output_file}'")
    print("="*80)
    
    return df

if __name__ == '__main__':
    main()
